### ISSUE TITLE
big_core - find how to pass a variable between the linker and package

### ISSUE THREAD

**Issue by danielk532** [amichai-bd/riscv_manycore_mesh_fpga#104]
find how to pass a variable between the linker and package

**Comment by amichai-bd** [comment]
I was able to pass a variable to the linker from the GCC - this will allow us to define a parameter that will be used both for the GCC SW linker & we can use it to override the parameter in the systemverilog package using the "pvalue" option that can overrides parameters.

We will need to make sure we do the same once we get to FPGA.

This picture shows the "-Wl,--defsym=" that passes variables. - 
![image](https://user-images.githubusercontent.com/81047407/211615248-8275b6f6-6da9-4a62-a026-7b040cc3c5cb.png)
you will need to update the build to support a new flag that will override both HW mem offsets & sizes.

Dont forget to pull from origin before starting to get my chages

**Comment by amichai-bd** [comment]
Closing this issue.
In issue #107 you will add the global defines per core configuration.
There you will use the defines to override the mem length & offset
