### ISSUE TITLE
find the root cause and solve the slt/sltu bug in the CPU

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#11]
Please mark yourself as done once you pushed a solution to a branch
Once you are all done, you may close the issue as completed

- [x] @danielk532 
- [ ] @yeonatanPerelman 
- [ ] @ShmuelSfez

**Comment by amichai-bd** [comment]
Did any of you find why the slt/sltu instructions did not work as expected?

**Comment by danielk532** [comment]
![image](https://user-images.githubusercontent.com/83028235/200180603-d6fdb9b4-a555-47e7-8e4f-ab79854ea634.png)

After a little debug, the output seems correct:)

**Comment by amichai-bd** [comment]
You fixed the bug?
Or just realized that the code was correct the whole time?

**Comment by danielk532** [comment]
I fixed it, but I didnt pushed my solution yet. I need some help with that.

**Comment by amichai-bd** [comment]
Glad you were able to find the bug!
Will ping you on WhatsApp later

**Comment by yeonatanPerelman** [comment]
fixed by daniel and alredy merged to main branch
![image](https://user-images.githubusercontent.com/111231093/203139607-bd70951f-c862-4373-b961-d982611c9f6e.png)
