### ISSUE TITLE
add a memory access tracker to the TB

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#12]
Make sure you add time, pc, opcode, address, and data.
The data in read is the load data, and the data in write is the store data.

Please mark yourself as done once you pushed a solution to a branch
Once you are all done, you may close the issue as complete

- [x]  @danielk532
- [x]  @yeonatanPerelman
- [x]  @ShmuelSfez

**Comment by amichai-bd** [comment]
Where are we at with this task?

**Comment by amichai-bd** [comment]
@ShmuelSfez @yeonatanPerelman 
You guys understand the task?
Please review what tracker were added already by Daniel and think create a new one

**Comment by ShmuelSfez** [comment]
all done.
