### ISSUE TITLE
Add a mesh directory under the source directory

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#14]
@yeonatanPerelman & @ShmuelSfez 
Add a directory called "mesh" under the "source" directory.
In the directory add a file called "README.md"
In the file, please write a short description of the project you are starting as you understand it. (1-3 paragraphs)

**Comment by amichai-bd** [comment]
+ mini_core directory under source

The same mini_cor & mesh under verif. 
verif
| mini_core
|----|-- tb
|----|-- tests

Add README.

**Comment by amichai-bd** [comment]
@yeonatanPerelman @ShmuelSfez 
This task should be simple - no need for simulation or anything.
Let me know what holds you back from this task.

**Comment by yeonatanPerelman** [comment]
I created the mini_core directory with Amichai help.
I will do with you the mesh directory @ShmuelSfez

**Comment by ShmuelSfez** [comment]
added mesh dirs and README
