### ISSUE TITLE
Watch ben Eater keyboard interface tutorial

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#18]
https://www.youtube.com/watch?v=7aXbh9VUB3U

**Comment by danielk532** [comment]
This is a good video, it explains the keyboard interfaces well.

**Comment by amichai-bd** [comment]
Please watch these too:
1)
https://www.youtube.com/watch?v=w1SB9Ry8_Jg

2) 
https://www.youtube.com/watch?v=dL0GO9SeBh0

**Comment by danielk532** [comment]
Done
