### ISSUE TITLE
create an alive tests for your future core.

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#22]
- [x] @danielk532 
- [x] @yeonatanPerelman  & @ShmuelSfez 

You may use the current implementation we designed together.

I would like to be able to read your README for each model and execute your "local" core.
Eventually, you will modify the core to be the one we need. (3/7 stage Pipeline)

**Comment by amichai-bd** [comment]
This means you need to copy the design we already have into your directory under source, then add your tb under verif.

Let me know if you have any questions on this.

**Comment by amichai-bd** [comment]
@yeonatanPerelman @ShmuelSfez - Use the RVC_ASAP as reference (not the Single-cycle we did together)
Add the tracker there to complete the other issue asigned to you

**Comment by amichai-bd** [comment]
@danielk532 - I see you marked yourself as done - but I don't see you're content in the main or your pull request.

**Comment by ShmuelSfez** [comment]
the test is alive!!!
