### ISSUE TITLE
Make sure you can compile GCC using RISCV toolchain

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#4]

**Comment by amichai-bd** [comment]
- [ ] @danielk532 
- [ ] @yeonatanPerelman 
- [ ] @ShmuelSfez

**Comment by danielk532** [comment]
The compilation is done

**Comment by amichai-bd** [comment]
@yeonatanPerelman @ShmuelSfez 
Please send a screenshot & mark yourself as done

**Comment by amichai-bd** [comment]
@yeonatanPerelman & @ShmuelSfez 
Reminder
