### ISSUE TITLE
Cache - Add a simple TB & DUT to the Cache directory

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#47]
Design a simple "xor" module + tracker
source/cache
verif/cache/tb
modelsim/cache
target/cache

**Comment by noamsabb** [comment]
Hi @amichai-bd  I'm not sure I know what are DUT and tracker
I added the module, list and TB files to the appropriates cache directories and succeed to compile and run simulation 
![Capture d’écran 2022-12-06 à 00 52 15](https://user-images.githubusercontent.com/83982485/205760091-9986c025-2eef-47ae-a828-73ae8a5690e1.png)
![Capture d’écran 2022-12-06 à 00 52 27](https://user-images.githubusercontent.com/83982485/205760145-be44f9ab-4832-460e-882d-176632591b6a.png)

**Comment by amichai-bd** [comment]
DUT - Device under test. the Component that is being created and tested by the verification.
The tracker - Is a generated log file that tracks some elements in your design.

Please see the big_core_tb as a reference for trackers. 

Once you are ready to "commit" please add to your commit message "close #47" which will close this issue.

**Comment by amichai-bd** [comment]
If this done, please close this issue.

**Comment by amichai-bd** [comment]
Done
