### ISSUE TITLE
Make sure you can simulate Systemverilog

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#5]

**Comment by amichai-bd** [comment]
- [ ] @danielk532
 - [ ]  @yeonatanPerelman
 - [ ]  @ShmuelSfez

**Comment by danielk532** [comment]
I run a simulation for NAND gate with and without gui - 
![image](https://user-images.githubusercontent.com/83028235/188741505-4e138124-b760-41ff-a3c2-7a3abd9f97cc.png)
![image](https://user-images.githubusercontent.com/83028235/188741536-fc0383b1-dac3-4d29-b1e5-e936153dca18.png)

**Comment by amichai-bd** [comment]
@yeonatanPerelman @ShmuelSfez 
Reminder

**Comment by yeonatanPerelman** [comment]
we fixed all our problems

**Comment by amichai-bd** [comment]
@yeonatanPerelman - Next time please document what was the issue you faced to complete the task.
For example  in this case:
- Make sure first to choose what signals you want to view.   
A simple way is to select hierarchy on the left side, then press the \<ctrl\>+'w' to "bring" all the hierarchy signals. 
- Then press the "Restart" button & Press the Run Button
![image](https://user-images.githubusercontent.com/81047407/203148897-db58096b-510f-4e03-bdf1-c41fc4688219.png)

- Alternatively, you may use the "VSIM" terminal to run all the commands:
![image](https://user-images.githubusercontent.com/81047407/203149096-a013fa16-460a-47fc-9966-405449387378.png)

**Comment by noamsabb** [comment]
i ran a simulation for XOR gate, i get good results without gui but can't see any waves in gui, look like the code is not running
![Test_b](https://user-images.githubusercontent.com/83982485/203765839-a50f899b-b71e-4e33-867a-507516068416.png)
![Screenshot (1)](https://user-images.githubusercontent.com/83982485/203768619-d560bd81-a69a-4236-b55f-d11ce91cd373.png)

**Comment by amichai-bd** [comment]
Did you try and press this:
![image](https://user-images.githubusercontent.com/81047407/203774049-ff35ca97-7743-4dc7-bf6f-971b302d12e4.png)
