### ISSUE TITLE
big_core - Create a "build/big_core_build.py"

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#54]
Has 3 flags:

-app | compile the RISCV SW into SV executables
-hw | compile the RISCV HW into simulation
-sim | start simulation

Choose which test to run - plus+args to point to the correct 'memory' that was generated. - Leave this for last.
Make sure the trk.log files get the unique directory of the specific test

**Comment by danielk532** [comment]
first version of the script is located at 'riscv_manycore_mesh_fpga/build.py'.
please use the flag -h before you run it.
for any improvements or questions please contact me.

**Comment by amichai-bd** [comment]
Once you commit the changes,
Please add the ```close #<issue_id>``` comment in the commit message.
