### ISSUE TITLE
Cache - Document the behavier of the merg_buffer & the Merge_buffer State in the HAS

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#82]
Explain the cases of WR after Wr to the same CL
Explain Rd After WR to same CACHE line with word miss (HIT MB + MISS WORD) 
Explain Rd After WR to same CACHE line with word HIT ( HIT MB + HIT WORD)(response from MB and not the Pipe)

How the fill is used for both WR miss fill & Read

How the RD miss will stall the Core.
How the MB merges the Writes & the Fills

How the FIll with a "rd_indication" will go through the pipe to answer and send the rd response in q3.

How do we never allocate a new entry for the request to the same CL. 
- In case of hit in "FILL_LU" the RD/WR request will 100% hit the Cache, no need to allocate a new TQ entry

The MB is a structure that works per TQ entry.

**Comment by noamsabb** [comment]
See edits on the HAS documents
