### ISSUE TITLE
big_core - align all the trackers to Q102

### ISSUE THREAD

**Issue by danielk532** [amichai-bd/riscv_manycore_mesh_fpga#90]
align all the trackers to Q102

**Comment by amichai-bd** [comment]
Make sure to remove all the TABs (```\t```) from the tracker

**Comment by amichai-bd** [comment]
@danielk532 - it looks like this issue did not close with our comment:
```close issues #86, #86, #90, #95```
Next time please write explicit like this:
``` close #86, close #86, close #90, close #95```

I will be closing it manually and tag the relevant commit
commit : https://github.com/amichai-bd/riscv_manycore_mesh_fpga/pull/95
