### ISSUE TITLE
big_core - add an option to run assembly files + no crt0

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv_manycore_mesh_fpga#97]
1. allow to run asm files from the script. (don't force only c files)
1. add a flag to the sw compile to run without crt0.S

**Comment by danielk532** [comment]
@amichai-bd - I have a problem with this task, I would like talk to you about it

**Comment by amichai-bd** [comment]
Sure, welcome to watsapp me.
Or simply write down here what is the issue you encounter.

**Comment by amichai-bd** [comment]
Won't support flag to run without crt0.
